---
- name: base
  hosts: all
  become: yes
  roles:
    - base
- name: jenkins
  hosts: jenkins
  become: yes
  roles:
    - nginx
    - jenkins
- name: download
  hosts: download
  become: yes
  roles:
    - nginx
    - download
- name: www
  hosts: www
  become: yes
  roles:
    - nginx
    - jenkins_ssh_slave
    - www
- name: build_android
  hosts: acc.umu.se
  roles:
    - build_android
